// Windissect recovered ABI metadata — DO NOT EDIT.
// Portable across C++17, C++20, C++23, and C++26 draft modes.
#pragma once
#include <cstddef>
#include <cstdint>

namespace windissect_abi {
struct TypeLayout { const char* name; std::uint64_t size; const char* kind; };
struct FieldLayout { const char* owner; const char* name; std::uint32_t type_index; std::uint64_t offset; bool is_static; };
struct FieldObservation { const char* owner; const char* suggested_name; std::uint64_t offset; std::uint32_t width; const char* access; std::uint32_t evidence_rva; const char* evidence_symbol; const char* confidence; };
struct BaseLayout { const char* derived; const char* base; std::int64_t offset; bool is_virtual; const char* evidence; const char* confidence; };
struct VTableLayout { const char* name; std::uint32_t rva; std::uint32_t slots; const char* evidence; const char* confidence; };
struct VTableSlotLayout { std::uint32_t table_rva; std::uint32_t slot; std::uint32_t target_rva; const char* target_id; const char* target_name; bool ambiguous; std::int32_t this_adjustment; };

inline constexpr TypeLayout types[] = {
    {".?AV?$__base@$$A6A_NPEAX_K01I@Z@__function@wistd@@", 0ULL, "class"},
    {".?AV?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@", 0ULL, "class"},
    {".?AVResultException@wil@@", 0ULL, "class"},
    {"ATL", 0ULL, "layout-evidence"},
    {"ATL::CComPtr<struct IWICImagingFactory>", 0ULL, "layout-evidence"},
    {"ATL::CComPtrBase<struct IWICImagingFactory>", 0ULL, "layout-evidence"},
    {"BaseBrdResourceIdMap", 0ULL, "layout-evidence"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", 0ULL, "layout-evidence"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>::CAutoPtr", 0ULL, "layout-evidence"},
    {"CEtwProviderT<void>", 0ULL, "layout-evidence"},
    {"CEtwProviderT<void>::CETWApiSet", 0ULL, "layout-evidence"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", 0ULL, "layout-evidence"},
    {"ResourceIdMap", 0ULL, "layout-evidence"},
    {"SH<struct HINSTANCE__*, class SH_HMODULE>", 0ULL, "layout-evidence"},
    {"SH<unsigned short *, class SH_SSTRING>", 0ULL, "layout-evidence"},
    {"SH_HMODULE", 0ULL, "layout-evidence"},
    {"SH_SSTRING", 0ULL, "layout-evidence"},
    {"SP<class ResourceIdMap, class SP_CPP<class ResourceIdMap> >", 0ULL, "layout-evidence"},
    {"SP<unsigned short, class SP_HLOCAL<unsigned short> >", 0ULL, "layout-evidence"},
    {"SP<unsigned short, class SP_WDS<unsigned short> >", 0ULL, "layout-evidence"},
    {"SP<void, class SP_MEM<void> >", 0ULL, "layout-evidence"},
    {"ShellBrdResourceIdMap", 0ULL, "layout-evidence"},
    {"exception", 0ULL, "layout-evidence"},
    {"type_info", 0ULL, "layout-evidence"},
    {"wil", 0ULL, "layout-evidence"},
    {"wil::ResultException", 0ULL, "layout-evidence"},
    {"wil::StoredFailureInfo", 0ULL, "layout-evidence"},
    {"wil::details", 0ULL, "layout-evidence"},
    {"wil::details::FeatureStateManager", 0ULL, "layout-evidence"},
    {"wil::details::in1diag3", 0ULL, "layout-evidence"},
    {"wil::details::shared_buffer", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*, void (__cdecl *)(struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*), void (__cdecl wil::details::UnsubscribeProcessWideUsageFlush::*)(struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*), struct wistd::integral_constant<uint64_t, 0>, struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*, struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct _RTL_CRITICAL_SECTION *, void (__cdecl *)(struct _RTL_CRITICAL_SECTION *), void (__cdecl LeaveCriticalSection::*)(struct _RTL_CRITICAL_SECTION *), struct wistd::integral_constant<uint64_t, 1>, struct _RTL_CRITICAL_SECTION *, struct _RTL_CRITICAL_SECTION *, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct _RTL_SRWLOCK *, void (__cdecl *)(struct _RTL_SRWLOCK *), void (__cdecl ReleaseSRWLockExclusive::*)(struct _RTL_SRWLOCK *), struct wistd::integral_constant<uint64_t, 1>, struct _RTL_SRWLOCK *, struct _RTL_SRWLOCK *, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct _TP_TIMER *, void (__cdecl *)(struct _TP_TIMER *), void (__cdecl wil::details::DestroyThreadPoolTimer<struct wil::details::SystemThreadPoolMethods, 0>::Destroy::*)(struct _TP_TIMER *), struct wistd::integral_constant<uint64_t, 0>, struct _TP_TIMER *, struct _TP_TIMER *, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<void *, void (__cdecl *)(void *), void (__cdecl wil::details::UnregisterWilFeatureConfigurationChange::*)(void *), struct wistd::integral_constant<uint64_t, 0>, void *, void *, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details_abi", 0ULL, "layout-evidence"},
    {"wil::details_abi::FeatureStateData", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalStorage<class wil::details_abi::FeatureStateData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalStorage<struct wil::details_abi::ProcessLocalData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalStorageData<class wil::details_abi::FeatureStateData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::RawUsageIndex", 0ULL, "layout-evidence"},
    {"wil::details_abi::SemaphoreValue", 0ULL, "layout-evidence"},
    {"wil::details_abi::SubscriptionList", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalData", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalFailureInfo", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<class wil::details::ThreadFailureCallbackHolder *>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<struct wil::details_abi::ThreadLocalData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::UsageIndex<enum wil_details_ServiceReportingKind, unsigned int, 0>", 0ULL, "layout-evidence"},
    {"wil::details_abi::UsageIndex<enum wil_details_ServiceReportingKind, unsigned int, 2>", 0ULL, "layout-evidence"},
    {"wil::details_abi::UsageIndexProperty", 0ULL, "layout-evidence"},
    {"wil::details_abi::UsageIndexes", 0ULL, "layout-evidence"},
    {"wil::details_abi::heap_buffer", 0ULL, "layout-evidence"},
    {"wil::last_error_context", 0ULL, "layout-evidence"},
    {"wistd", 0ULL, "layout-evidence"},
    {"wistd::__compressed_pair<void *, struct wil::process_heap_deleter>", 0ULL, "layout-evidence"},
    {"wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>", 0ULL, "layout-evidence"},
    {"wistd::function<bool __cdecl (void *, uint64_t, void *, uint64_t, unsigned int)>", 0ULL, "layout-evidence"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", 0ULL, "layout-evidence"},
    {nullptr, 0, nullptr},
};
inline constexpr std::size_t type_count = (sizeof(types) / sizeof(types[0])) - 1;
inline constexpr FieldLayout fields[] = {
    {nullptr, nullptr, 0, 0, false},
};
inline constexpr std::size_t field_count = (sizeof(fields) / sizeof(fields[0])) - 1;
inline constexpr FieldObservation field_observations[] = {
    {"ATL", nullptr, 0ULL, 8U, "read", 0x1F904U, "?AtlComPtrAssign@ATL@@YAPEAUIUnknown@@PEAPEAU2@PEAU2@@Z", "likely"},
    {"ATL", nullptr, 0ULL, 8U, "write", 0x1F904U, "?AtlComPtrAssign@ATL@@YAPEAUIUnknown@@PEAPEAU2@PEAU2@@Z", "likely"},
    {"ATL::CComPtrBase<struct IWICImagingFactory>", nullptr, 0ULL, 8U, "read", 0x1F464U, "??1?$CComPtrBase@UIWICImagingFactory@@@ATL@@QEAA@XZ", "likely"},
    {"BaseBrdResourceIdMap", nullptr, 8ULL, 8U, "read", 0xFA54U, "?UpdateResourceIdOptional@BaseBrdResourceIdMap@@AEAAXKIPEAI@Z", "likely"},
    {"BaseBrdResourceIdMap", nullptr, 16ULL, 8U, "read", 0xF8E0U, "?UpdateResourceId@BaseBrdResourceIdMap@@UEAAXKIPEAI@Z", "likely"},
    {"BaseBrdResourceIdMap", nullptr, 24ULL, 4U, "read", 0xF8E0U, "?UpdateResourceId@BaseBrdResourceIdMap@@UEAAXKIPEAI@Z", "likely"},
    {"BaseBrdResourceIdMap", nullptr, 28ULL, 4U, "read", 0xFA54U, "?UpdateResourceIdOptional@BaseBrdResourceIdMap@@AEAAXKIPEAI@Z", "likely"},
    {"BaseBrdResourceIdMap", nullptr, 32ULL, 4U, "read", 0xF8E0U, "?UpdateResourceId@BaseBrdResourceIdMap@@UEAAXKIPEAI@Z", "likely"},
    {"BaseBrdResourceIdMap", nullptr, 32ULL, 4U, "read", 0xFA54U, "?UpdateResourceIdOptional@BaseBrdResourceIdMap@@AEAAXKIPEAI@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 0ULL, 4U, "read", 0x24080U, "?Insert@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJHAEBVDH_SSTRING@@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 0ULL, 4U, "read", 0x24294U, "?SetSize@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJH@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 0ULL, 4U, "write", 0x24294U, "?SetSize@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJH@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 0ULL, 4U, "read", 0x24394U, "?Swap@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAXPEAV1@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 0ULL, 4U, "write", 0x24394U, "?Swap@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAXPEAV1@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 4ULL, 4U, "read", 0x24080U, "?Insert@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJHAEBVDH_SSTRING@@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 4ULL, 4U, "read-write", 0x24080U, "?Insert@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJHAEBVDH_SSTRING@@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 4ULL, 4U, "read", 0x24294U, "?SetSize@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJH@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 4ULL, 4U, "write", 0x24294U, "?SetSize@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJH@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 4ULL, 4U, "read", 0x24394U, "?Swap@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAXPEAV1@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 4ULL, 4U, "write", 0x24394U, "?Swap@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAXPEAV1@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 8ULL, 8U, "read", 0x24080U, "?Insert@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJHAEBVDH_SSTRING@@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 8ULL, 8U, "read", 0x24294U, "?SetSize@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAJH@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 8ULL, 8U, "read", 0x24394U, "?Swap@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAXPEAV1@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>", nullptr, 8ULL, 8U, "read-write", 0x24394U, "?Swap@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAXPEAV1@@Z", "likely"},
    {"CArray<class DH_SSTRING, class DH_SSTRING, class CAdaptorDefault, class CPoliciesDefault>::CAutoPtr", nullptr, 0ULL, 8U, "write", 0x239F0U, "??4CAutoPtr@?$CArray@VDH_SSTRING@@V1@VCAdaptorDefault@@VCPoliciesDefault@@@@QEAAAEAV01@PEAVDH_SSTRING@@@Z", "likely"},
    {"CEtwProviderT<void>", nullptr, 0ULL, 8U, "read", 0x1B958U, "?Unregister@?$CEtwProviderT@X@@QEAAXXZ", "likely"},
    {"CEtwProviderT<void>", nullptr, 0ULL, 8U, "read-write", 0x1B958U, "?Unregister@?$CEtwProviderT@X@@QEAAXXZ", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 0ULL, 8U, "read-write", 0x239A0U, "??0?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@QEAA@XZ", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 0ULL, 8U, "read", 0x23A20U, "?Check2Grow@?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@AEAAJKH@Z", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 0ULL, 8U, "write", 0x23A20U, "?Check2Grow@?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@AEAAJKH@Z", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 0ULL, 8U, "read", 0x24464U, "?Append@?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@QEAAJPEBG@Z", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 8ULL, 4U, "read-write", 0x239A0U, "??0?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@QEAA@XZ", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 8ULL, 4U, "read", 0x23A20U, "?Check2Grow@?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@AEAAJKH@Z", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 8ULL, 4U, "read", 0x24464U, "?Append@?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@QEAAJPEBG@Z", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 8ULL, 4U, "write", 0x24464U, "?Append@?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@QEAAJPEBG@Z", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 12ULL, 4U, "read-write", 0x239A0U, "??0?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@QEAA@XZ", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 12ULL, 4U, "read", 0x23A20U, "?Check2Grow@?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@AEAAJKH@Z", "likely"},
    {"CStringBufferImplT<unsigned short, class CStringBufferPolicyDefaultT<unsigned short>, class CStringHelperDefaultT<class CStringBufferPolicyDefaultT<unsigned short> > >", nullptr, 12ULL, 4U, "write", 0x23A20U, "?Check2Grow@?$CStringBufferImplT@GV?$CStringBufferPolicyDefaultT@G@@V?$CStringHelperDefaultT@V?$CStringBufferPolicyDefaultT@G@@@@@@AEAAJKH@Z", "likely"},
    {"ResourceIdMap", nullptr, 0ULL, 8U, "write", 0x238BCU, "??1ResourceIdMap@@UEAA@XZ", "likely"},
    {"ResourceIdMap", nullptr, 32ULL, 4U, "read-write", 0x238BCU, "??1ResourceIdMap@@UEAA@XZ", "likely"},
    {"SH<struct HINSTANCE__*, class SH_HMODULE>", nullptr, 0ULL, 8U, "read", 0xFB40U, "?Reset@?$SH@PEAUHINSTANCE__@@VSH_HMODULE@@@@QEAAXXZ", "likely"},
    {"SH<struct HINSTANCE__*, class SH_HMODULE>", nullptr, 0ULL, 8U, "write", 0xFB40U, "?Reset@?$SH@PEAUHINSTANCE__@@VSH_HMODULE@@@@QEAAXXZ", "likely"},
    {"SH<unsigned short *, class SH_SSTRING>", nullptr, 0ULL, 8U, "read", 0x80B0U, "?Reset@?$SH@PEAGVSH_SSTRING@@@@QEAAXXZ", "likely"},
    {"SH<unsigned short *, class SH_SSTRING>", nullptr, 0ULL, 8U, "write", 0x80B0U, "?Reset@?$SH@PEAGVSH_SSTRING@@@@QEAAXXZ", "likely"},
    {"SH_HMODULE", nullptr, 0ULL, 8U, "read", 0x1B218U, "??1SH_HMODULE@@QEAA@XZ", "likely"},
    {"SH_HMODULE", nullptr, 0ULL, 8U, "read-write", 0x1B218U, "??1SH_HMODULE@@QEAA@XZ", "likely"},
    {"SH_SSTRING", nullptr, 0ULL, 8U, "read", 0x7FA8U, "??4SH_SSTRING@@QEAAAEAV0@$$T@Z", "likely"},
    {"SH_SSTRING", nullptr, 0ULL, 8U, "read-write", 0x7FA8U, "??4SH_SSTRING@@QEAAAEAV0@$$T@Z", "likely"},
    {"SH_SSTRING", nullptr, 0ULL, 8U, "read", 0x8654U, "??1SH_SSTRING@@QEAA@XZ", "likely"},
    {"SH_SSTRING", nullptr, 0ULL, 8U, "read-write", 0x8654U, "??1SH_SSTRING@@QEAA@XZ", "likely"},
    {"SP<class ResourceIdMap, class SP_CPP<class ResourceIdMap> >", nullptr, 0ULL, 8U, "read", 0x1B1E4U, "?Reset@?$SP@VResourceIdMap@@V?$SP_CPP@VResourceIdMap@@@@@@QEAAXXZ", "likely"},
    {"SP<class ResourceIdMap, class SP_CPP<class ResourceIdMap> >", nullptr, 0ULL, 8U, "read-write", 0x1B1E4U, "?Reset@?$SP@VResourceIdMap@@V?$SP_CPP@VResourceIdMap@@@@@@QEAAXXZ", "likely"},
    {"SP<unsigned short, class SP_HLOCAL<unsigned short> >", nullptr, 0ULL, 8U, "read", 0x15534U, "?Reset@?$SP@GV?$SP_HLOCAL@G@@@@QEAAXXZ", "likely"},
    {"SP<unsigned short, class SP_HLOCAL<unsigned short> >", nullptr, 0ULL, 8U, "read-write", 0x15534U, "?Reset@?$SP@GV?$SP_HLOCAL@G@@@@QEAAXXZ", "likely"},
    {"SP<unsigned short, class SP_WDS<unsigned short> >", nullptr, 0ULL, 8U, "read", 0x9AD8U, "?Reset@?$SP@GV?$SP_WDS@G@@@@QEAAXXZ", "likely"},
    {"SP<unsigned short, class SP_WDS<unsigned short> >", nullptr, 0ULL, 8U, "read-write", 0x9AD8U, "?Reset@?$SP@GV?$SP_WDS@G@@@@QEAAXXZ", "likely"},
    {"SP<void, class SP_MEM<void> >", nullptr, 0ULL, 8U, "read", 0x7FD4U, "?Reset@?$SP@XV?$SP_MEM@X@@@@QEAAXXZ", "likely"},
    {"SP<void, class SP_MEM<void> >", nullptr, 0ULL, 8U, "read-write", 0x7FD4U, "?Reset@?$SP@XV?$SP_MEM@X@@@@QEAAXXZ", "likely"},
    {"ShellBrdResourceIdMap", nullptr, 16ULL, 8U, "read", 0x23950U, "?UpdateResourceId@ShellBrdResourceIdMap@@UEAAXKIPEAI@Z", "likely"},
    {"ShellBrdResourceIdMap", nullptr, 24ULL, 4U, "read", 0x23950U, "?UpdateResourceId@ShellBrdResourceIdMap@@UEAAXKIPEAI@Z", "likely"},
    {"ShellBrdResourceIdMap", nullptr, 32ULL, 4U, "read", 0x23950U, "?UpdateResourceId@ShellBrdResourceIdMap@@UEAAXKIPEAI@Z", "likely"},
    {"wil", nullptr, 0ULL, 2U, "read", 0x20244U, "?GetFailureLogString@wil@@YAJPEAG_KAEBUFailureInfo@1@@Z", "likely"},
    {"wil::ResultException", nullptr, 0ULL, 8U, "write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 24ULL, 16U, "write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 40ULL, 16U, "write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 56ULL, 16U, "write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 72ULL, 16U, "write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 88ULL, 16U, "write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 104ULL, 16U, "write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 120ULL, 16U, "write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 192ULL, 8U, "read-write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 200ULL, 8U, "read-write", 0x1F314U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 0ULL, 16U, "write", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 16ULL, 16U, "write", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 32ULL, 16U, "write", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 48ULL, 16U, "write", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 64ULL, 16U, "write", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 80ULL, 16U, "write", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 96ULL, 16U, "write", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 152ULL, 8U, "read", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 160ULL, 8U, "read", 0x216C8U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 8U, "read", 0x1B8D4U, "??$EnsureCoalescedTimer@VFeatureStateManager@details@wil@@@details@wil@@YAXAEAV?$unique_any_t@V?$unique_storage@U?$resource_policy@PEAU_TP_TIMER@@P6AXPEAU1@@Z$1?Destroy@?$DestroyThreadPoolTimer@USystemThreadPoolMethods@details@wil@@$0A@@details@wil@@SAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@@1@AEA_NPEAVFeatureStateManager@01@@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 8U, "read", 0x1C170U, "?EnsureCoalescedTimer_SetTimer@details@wil@@YAXAEAV?$unique_any_t@V?$unique_storage@U?$resource_policy@PEAU_TP_TIMER@@P6AXPEAU1@@Z$1?Destroy@?$DestroyThreadPoolTimer@USystemThreadPoolMethods@details@wil@@$0A@@details@wil@@SAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@@2@AEA_N_J@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 8U, "read", 0x1EE04U, "??$EnsureCoalescedTimerSRUM@VFeatureStateManager@details@wil@@@details@wil@@YAXAEAV?$unique_any_t@V?$unique_storage@U?$resource_policy@PEAU_TP_TIMER@@P6AXPEAU1@@Z$1?Destroy@?$DestroyThreadPoolTimer@USystemThreadPoolMethods@details@wil@@$0A@@details@wil@@SAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@@1@AEA_NPEAVFeatureStateManager@01@@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 1U, "read", 0x20DA0U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 8U, "read-write", 0x21E30U, "?WilApiImpl_SubscribeFeatureStateChangeNotification@details@wil@@YAXPEAPEAUFEATURE_STATE_CHANGE_SUBSCRIPTION__@@P6AXPEAX@Z1@Z", "likely"},
    {"wil::details", nullptr, 4ULL, 4U, "read-write", 0x20DA0U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 8ULL, 4U, "read", 0x20DA0U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 8ULL, 4U, "read", 0x21FCCU, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 16ULL, 4U, "write", 0x20DA0U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 24ULL, 8U, "read", 0x20DA0U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 56ULL, 8U, "read", 0x20DA0U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 64ULL, 2U, "read", 0x20DA0U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 64ULL, 4U, "read", 0x21FCCU, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 128ULL, 8U, "read", 0x20DA0U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 136ULL, 8U, "read", 0x21FCCU, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 0ULL, 1U, "write", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 0ULL, 1U, "read", 0x1B734U, "?RecordFeatureUsage@FeatureStateManager@details@wil@@QEAAXIW4wil_details_ServiceReportingKind@@_K@Z", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 0ULL, 1U, "read", 0x1C9A4U, "?SubscribeToUsageFlush@FeatureStateManager@details@wil@@QEAAXPEAPEAUFEATURE_STATE_CHANGE_SUBSCRIPTION__@@P6AXPEAX@Z@Z", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 0ULL, 1U, "read", 0x20E48U, "?OnTimer@FeatureStateManager@details@wil@@QEAAXXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 0ULL, 1U, "read", 0x20FA4U, "?QueueBackgroundSRUMUsageReporting@FeatureStateManager@details@wil@@QEAAXIGI@Z", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 8ULL, 8U, "read", 0x1B7D4U, "?EnsureStateData@FeatureStateManager@details@wil@@AEAA_NXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 16ULL, 8U, "read", 0x1B7D4U, "?EnsureStateData@FeatureStateManager@details@wil@@AEAA_NXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 16ULL, 8U, "write", 0x1B7D4U, "?EnsureStateData@FeatureStateManager@details@wil@@AEAA_NXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 16ULL, 8U, "read", 0x1B7D4U, "?EnsureStateData@FeatureStateManager@details@wil@@AEAA_NXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 24ULL, 8U, "read", 0x1B734U, "?RecordFeatureUsage@FeatureStateManager@details@wil@@QEAAXIW4wil_details_ServiceReportingKind@@_K@Z", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 24ULL, 8U, "read", 0x1B7D4U, "?EnsureStateData@FeatureStateManager@details@wil@@AEAA_NXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 24ULL, 8U, "write", 0x1B7D4U, "?EnsureStateData@FeatureStateManager@details@wil@@AEAA_NXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 24ULL, 8U, "read", 0x1B7D4U, "?EnsureStateData@FeatureStateManager@details@wil@@AEAA_NXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 24ULL, 8U, "read", 0x1CA60U, "?FlushUsage@FeatureStateManager@details@wil@@QEAAXXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 24ULL, 8U, "read", 0x1FE18U, "?EnsureSubscribedToProcessWideUsageFlushUnderLock@FeatureStateManager@details@wil@@AEAAXXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 48ULL, 8U, "read", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 48ULL, 8U, "read-write", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 48ULL, 8U, "read", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 56ULL, 8U, "read", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 56ULL, 8U, "read-write", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 56ULL, 8U, "read", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 65ULL, 1U, "write", 0x20E48U, "?OnTimer@FeatureStateManager@details@wil@@QEAAXXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 224ULL, 8U, "read", 0x1FE18U, "?EnsureSubscribedToProcessWideUsageFlushUnderLock@FeatureStateManager@details@wil@@AEAAXXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 224ULL, 8U, "read-write", 0x1FE18U, "?EnsureSubscribedToProcessWideUsageFlushUnderLock@FeatureStateManager@details@wil@@AEAAXXZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 256ULL, 8U, "read", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::FeatureStateManager", nullptr, 256ULL, 8U, "read-write", 0x1B3E8U, "??1FeatureStateManager@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::shared_buffer", nullptr, 0ULL, 8U, "write", 0x22304U, "?assign@shared_buffer@details@wil@@AEAAXPEAJ_K@Z", "likely"},
    {"wil::details::shared_buffer", nullptr, 0ULL, 8U, "read", 0x224E8U, "?reset@shared_buffer@details@wil@@QEAAXXZ", "likely"},
    {"wil::details::shared_buffer", nullptr, 0ULL, 8U, "read-write", 0x224E8U, "?reset@shared_buffer@details@wil@@QEAAXXZ", "likely"},
    {"wil::details::shared_buffer", nullptr, 8ULL, 8U, "write", 0x22304U, "?assign@shared_buffer@details@wil@@AEAAXPEAJ_K@Z", "likely"},
    {"wil::details::shared_buffer", nullptr, 8ULL, 8U, "read-write", 0x224E8U, "?reset@shared_buffer@details@wil@@QEAAXXZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*, void (__cdecl *)(struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*), void (__cdecl wil::details::UnsubscribeProcessWideUsageFlush::*)(struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*), struct wistd::integral_constant<uint64_t, 0>, struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*, struct FEATURE_STATE_CHANGE_SUBSCRIPTION__*, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0x1B540U, "??1?$unique_storage@U?$resource_policy@PEAUFEATURE_STATE_CHANGE_SUBSCRIPTION__@@P6AXPEAU1@@Z$1?UnsubscribeProcessWideUsageFlush@details@wil@@YAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct _RTL_CRITICAL_SECTION *, void (__cdecl *)(struct _RTL_CRITICAL_SECTION *), void (__cdecl LeaveCriticalSection::*)(struct _RTL_CRITICAL_SECTION *), struct wistd::integral_constant<uint64_t, 1>, struct _RTL_CRITICAL_SECTION *, struct _RTL_CRITICAL_SECTION *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0x1DBC0U, "??1?$unique_storage@U?$resource_policy@PEAU_RTL_CRITICAL_SECTION@@P6AXPEAU1@@Z$1?LeaveCriticalSection@@YAX0@ZU?$integral_constant@_K$00@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct _RTL_SRWLOCK *, void (__cdecl *)(struct _RTL_SRWLOCK *), void (__cdecl ReleaseSRWLockExclusive::*)(struct _RTL_SRWLOCK *), struct wistd::integral_constant<uint64_t, 1>, struct _RTL_SRWLOCK *, struct _RTL_SRWLOCK *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0x1DC0CU, "??1?$unique_storage@U?$resource_policy@PEAU_RTL_SRWLOCK@@P6AXPEAU1@@Z$1?ReleaseSRWLockExclusive@@YAX0@ZU?$integral_constant@_K$00@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct _TP_TIMER *, void (__cdecl *)(struct _TP_TIMER *), void (__cdecl wil::details::DestroyThreadPoolTimer<struct wil::details::SystemThreadPoolMethods, 0>::Destroy::*)(struct _TP_TIMER *), struct wistd::integral_constant<uint64_t, 0>, struct _TP_TIMER *, struct _TP_TIMER *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0x1B6DCU, "?reset@?$unique_storage@U?$resource_policy@PEAU_TP_TIMER@@P6AXPEAU1@@Z$1?Destroy@?$DestroyThreadPoolTimer@USystemThreadPoolMethods@details@wil@@$0A@@details@wil@@SAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@QEAAXPEAU_TP_TIMER@@@Z", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct _TP_TIMER *, void (__cdecl *)(struct _TP_TIMER *), void (__cdecl wil::details::DestroyThreadPoolTimer<struct wil::details::SystemThreadPoolMethods, 0>::Destroy::*)(struct _TP_TIMER *), struct wistd::integral_constant<uint64_t, 0>, struct _TP_TIMER *, struct _TP_TIMER *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "write", 0x1B6DCU, "?reset@?$unique_storage@U?$resource_policy@PEAU_TP_TIMER@@P6AXPEAU1@@Z$1?Destroy@?$DestroyThreadPoolTimer@USystemThreadPoolMethods@details@wil@@$0A@@details@wil@@SAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@QEAAXPEAU_TP_TIMER@@@Z", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<void *, void (__cdecl *)(void *), void (__cdecl wil::details::UnregisterWilFeatureConfigurationChange::*)(void *), struct wistd::integral_constant<uint64_t, 0>, void *, void *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0x1B520U, "??1?$unique_storage@U?$resource_policy@PEAXP6AXPEAX@Z$1?UnregisterWilFeatureConfigurationChange@details@wil@@YAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAXPEAX$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::FeatureStateData", nullptr, 64ULL, 1U, "read", 0x1D178U, "?RetrieveUsageUnderLock@FeatureStateData@details_abi@wil@@AEAAXAEAUUsageIndexes@23@@Z", "likely"},
    {"wil::details_abi::FeatureStateData", nullptr, 64ULL, 1U, "read", 0x21094U, "?RecordFeatureUsageUnderLock@FeatureStateData@details_abi@wil@@QEAA_NIW4wil_details_ServiceReportingKind@@_K@Z", "likely"},
    {"wil::details_abi::FeatureStateData", nullptr, 128ULL, 1U, "read", 0x1D178U, "?RetrieveUsageUnderLock@FeatureStateData@details_abi@wil@@AEAAXAEAUUsageIndexes@23@@Z", "likely"},
    {"wil::details_abi::FeatureStateData", nullptr, 192ULL, 1U, "read", 0x1D178U, "?RetrieveUsageUnderLock@FeatureStateData@details_abi@wil@@AEAAXAEAUUsageIndexes@23@@Z", "likely"},
    {"wil::details_abi::ProcessLocalStorage<class wil::details_abi::FeatureStateData>", nullptr, 8ULL, 8U, "read", 0x1C44CU, "??1?$ProcessLocalStorage@VFeatureStateData@details_abi@wil@@@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::ProcessLocalStorage<struct wil::details_abi::ProcessLocalData>", nullptr, 8ULL, 8U, "read", 0x1BF60U, "??1?$ProcessLocalStorage@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<class wil::details_abi::FeatureStateData>", nullptr, 0ULL, 4U, "read", 0x211F4U, "?Release@?$ProcessLocalStorageData@VFeatureStateData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<class wil::details_abi::FeatureStateData>", nullptr, 0ULL, 4U, "write", 0x211F4U, "?Release@?$ProcessLocalStorageData@VFeatureStateData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<class wil::details_abi::FeatureStateData>", nullptr, 0ULL, 4U, "read", 0x211F4U, "?Release@?$ProcessLocalStorageData@VFeatureStateData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<class wil::details_abi::FeatureStateData>", nullptr, 0ULL, 4U, "write", 0x211F4U, "?Release@?$ProcessLocalStorageData@VFeatureStateData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<class wil::details_abi::FeatureStateData>", nullptr, 0ULL, 4U, "read", 0x211F4U, "?Release@?$ProcessLocalStorageData@VFeatureStateData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x21168U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "write", 0x21168U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x21168U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "write", 0x21168U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x21168U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 0ULL, 2U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 0ULL, 2U, "read", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 2ULL, 2U, "read", 0x1BF80U, "?Iterate@RawUsageIndex@details_abi@wil@@QEBA_NV?$function@$$A6A_NPEAX_K01I@Z@wistd@@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 2ULL, 2U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 2ULL, 2U, "read", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 2ULL, 2U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 4ULL, 1U, "read", 0x1BF80U, "?Iterate@RawUsageIndex@details_abi@wil@@QEBA_NV?$function@$$A6A_NPEAX_K01I@Z@wistd@@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 4ULL, 1U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 4ULL, 1U, "read", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 4ULL, 1U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 6ULL, 2U, "read", 0x1BF80U, "?Iterate@RawUsageIndex@details_abi@wil@@QEBA_NV?$function@$$A6A_NPEAX_K01I@Z@wistd@@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 6ULL, 2U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 6ULL, 2U, "read", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 6ULL, 2U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 6ULL, 2U, "read", 0x1FEBCU, "?FindInsertionPointOrIncrement@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAEPEAX_KI@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 6ULL, 2U, "read", 0x20A28U, "?LowerBound@RawUsageIndex@details_abi@wil@@AEAAPEAEPEAE_KPEAX1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 6ULL, 2U, "read", 0x21A38U, "?SkipValues@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAE@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 8ULL, 1U, "read", 0x1BF80U, "?Iterate@RawUsageIndex@details_abi@wil@@QEBA_NV?$function@$$A6A_NPEAX_K01I@Z@wistd@@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 8ULL, 1U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 8ULL, 1U, "read", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 8ULL, 1U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 8ULL, 1U, "read", 0x1FEBCU, "?FindInsertionPointOrIncrement@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAEPEAX_KI@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 8ULL, 1U, "read", 0x20A28U, "?LowerBound@RawUsageIndex@details_abi@wil@@AEAAPEAEPEAE_KPEAX1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 8ULL, 1U, "read", 0x21A38U, "?SkipValues@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAE@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 16ULL, 8U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 16ULL, 8U, "read", 0x1FEBCU, "?FindInsertionPointOrIncrement@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAEPEAX_KI@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 16ULL, 8U, "read", 0x20A28U, "?LowerBound@RawUsageIndex@details_abi@wil@@AEAAPEAEPEAE_KPEAX1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 16ULL, 8U, "read", 0x21A38U, "?SkipValues@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAE@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 24ULL, 8U, "read", 0x1BF80U, "?Iterate@RawUsageIndex@details_abi@wil@@QEBA_NV?$function@$$A6A_NPEAX_K01I@Z@wistd@@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 24ULL, 8U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 24ULL, 8U, "read", 0x1C574U, "?RecordUsage@RawUsageIndex@details_abi@wil@@QEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 24ULL, 8U, "write", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 24ULL, 8U, "read", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 24ULL, 8U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 24ULL, 8U, "read", 0x21A38U, "?SkipValues@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAE@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 24ULL, 16U, "write", 0x21BF8U, "?Swap@RawUsageIndex@details_abi@wil@@QEAAXAEAV123@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "read", 0x1BF80U, "?Iterate@RawUsageIndex@details_abi@wil@@QEBA_NV?$function@$$A6A_NPEAX_K01I@Z@wistd@@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "write", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "write", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "write", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "read", 0x1FEBCU, "?FindInsertionPointOrIncrement@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAEPEAX_KI@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "read", 0x20A28U, "?LowerBound@RawUsageIndex@details_abi@wil@@AEAAPEAEPEAE_KPEAX1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 32ULL, 8U, "read", 0x21A38U, "?SkipValues@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAE@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 40ULL, 8U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 40ULL, 8U, "write", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 40ULL, 8U, "read", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 40ULL, 8U, "write", 0x21BF8U, "?Swap@RawUsageIndex@details_abi@wil@@QEAAXAEAV123@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 48ULL, 8U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 48ULL, 8U, "read", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 48ULL, 8U, "write", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 48ULL, 8U, "read", 0x1DB78U, "??1RawUsageIndex@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 48ULL, 8U, "read-write", 0x1DB78U, "??1RawUsageIndex@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 56ULL, 2U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 56ULL, 1U, "write", 0x1D758U, "?RecordUsageInternal@RawUsageIndex@details_abi@wil@@AEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 56ULL, 1U, "read", 0x1FEBCU, "?FindInsertionPointOrIncrement@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAEPEAX_KI@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 56ULL, 1U, "write", 0x1FEBCU, "?FindInsertionPointOrIncrement@RawUsageIndex@details_abi@wil@@AEAAPEAEAEAUUsageIndexProperty@23@PEAEPEAX_KI@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 56ULL, 1U, "read", 0x21BF8U, "?Swap@RawUsageIndex@details_abi@wil@@QEAAXAEAV123@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 56ULL, 1U, "write", 0x21BF8U, "?Swap@RawUsageIndex@details_abi@wil@@QEAAXAEAV123@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 57ULL, 1U, "write", 0x1D64CU, "?SetBuffer@RawUsageIndex@details_abi@wil@@QEAAXPEAX_K1@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 57ULL, 1U, "read", 0x21BF8U, "?Swap@RawUsageIndex@details_abi@wil@@QEAAXAEAV123@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 57ULL, 1U, "write", 0x21BF8U, "?Swap@RawUsageIndex@details_abi@wil@@QEAAXAEAV123@@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 58ULL, 1U, "write", 0x1C37CU, "??0RawUsageIndex@details_abi@wil@@QEAA@GGW4CountSize@12@G0@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 58ULL, 1U, "write", 0x1C574U, "?RecordUsage@RawUsageIndex@details_abi@wil@@QEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::RawUsageIndex", nullptr, 58ULL, 1U, "read", 0x1C574U, "?RecordUsage@RawUsageIndex@details_abi@wil@@QEAA_NPEAX_K01I@Z", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 40ULL, 8U, "read", 0x1B248U, "?OnSignaled@SubscriptionList@details_abi@wil@@QEAAXAEAVsrwlock@3@@Z", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 40ULL, 8U, "write", 0x1B6A0U, "??0SubscriptionList@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 40ULL, 8U, "read", 0x1C4A0U, "?SubscribeUnderLock@SubscriptionList@details_abi@wil@@QEAAXPEAPEAUFEATURE_STATE_CHANGE_SUBSCRIPTION__@@P6AXPEAX@Z1@Z", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 40ULL, 8U, "read", 0x21D08U, "?Unsubscribe@SubscriptionList@details_abi@wil@@QEAAXAEAVsrwlock@3@PEAUFEATURE_STATE_CHANGE_SUBSCRIPTION__@@@Z", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 48ULL, 8U, "read", 0x1B248U, "?OnSignaled@SubscriptionList@details_abi@wil@@QEAAXAEAVsrwlock@3@@Z", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 48ULL, 8U, "write", 0x1B6A0U, "??0SubscriptionList@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 48ULL, 8U, "read", 0x1C4A0U, "?SubscribeUnderLock@SubscriptionList@details_abi@wil@@QEAAXPEAPEAUFEATURE_STATE_CHANGE_SUBSCRIPTION__@@P6AXPEAX@Z1@Z", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 48ULL, 8U, "read", 0x21D08U, "?Unsubscribe@SubscriptionList@details_abi@wil@@QEAAXAEAVsrwlock@3@PEAUFEATURE_STATE_CHANGE_SUBSCRIPTION__@@@Z", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 56ULL, 8U, "write", 0x1B6A0U, "??0SubscriptionList@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 64ULL, 8U, "read", 0x1B4E8U, "??1SubscriptionList@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 64ULL, 8U, "read-write", 0x1B4E8U, "??1SubscriptionList@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::SubscriptionList", nullptr, 64ULL, 8U, "write", 0x1B6A0U, "??0SubscriptionList@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 8ULL, 8U, "read", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 16ULL, 4U, "read", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x1F960U, "?Clear@ThreadLocalData@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "write", 0x1F960U, "?Clear@ThreadLocalData@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "write", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 2U, "read", 0x1F960U, "?Clear@ThreadLocalData@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 4U, "write", 0x1F960U, "?Clear@ThreadLocalData@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 4U, "write", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 2U, "read", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 34ULL, 2U, "read", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 34ULL, 2U, "write", 0x21938U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 4ULL, 4U, "write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 8ULL, 4U, "write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 16ULL, 8U, "read-write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 24ULL, 2U, "write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 26ULL, 1U, "write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 32ULL, 8U, "read-write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 40ULL, 8U, "write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 48ULL, 8U, "write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 56ULL, 8U, "read-write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 64ULL, 8U, "read", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 64ULL, 8U, "write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 64ULL, 8U, "read", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 72ULL, 8U, "read", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 72ULL, 8U, "write", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 72ULL, 8U, "read", 0x21570U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 0ULL, 2U, "read", 0x1C070U, "?Read@UsageIndexProperty@details_abi@wil@@QEAA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", "Size", 0ULL, 2U, "read", 0x1C46CU, "?GetSize@UsageIndexProperty@details_abi@wil@@QEBA_KXZ", "certain"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 0ULL, 2U, "read", 0x220FCU, "?Write@UsageIndexProperty@details_abi@wil@@QEBA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 2ULL, 1U, "read", 0x1C070U, "?Read@UsageIndexProperty@details_abi@wil@@QEAA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", "Size", 2ULL, 1U, "read", 0x1C46CU, "?GetSize@UsageIndexProperty@details_abi@wil@@QEBA_KXZ", "certain"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 2ULL, 1U, "read", 0x21DCCU, "?UpdateCount@UsageIndexProperty@details_abi@wil@@QEAAXI@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 2ULL, 1U, "read", 0x220FCU, "?Write@UsageIndexProperty@details_abi@wil@@QEBA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 4ULL, 4U, "write", 0x1C070U, "?Read@UsageIndexProperty@details_abi@wil@@QEAA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 4ULL, 4U, "read", 0x21DCCU, "?UpdateCount@UsageIndexProperty@details_abi@wil@@QEAAXI@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 4ULL, 4U, "write", 0x21DCCU, "?UpdateCount@UsageIndexProperty@details_abi@wil@@QEAAXI@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 4ULL, 2U, "read", 0x220FCU, "?Write@UsageIndexProperty@details_abi@wil@@QEBA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 8ULL, 2U, "write", 0x1C070U, "?Read@UsageIndexProperty@details_abi@wil@@QEAA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 8ULL, 2U, "read", 0x1C070U, "?Read@UsageIndexProperty@details_abi@wil@@QEAA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", "Size", 8ULL, 2U, "read", 0x1C46CU, "?GetSize@UsageIndexProperty@details_abi@wil@@QEBA_KXZ", "certain"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 8ULL, 2U, "read", 0x1C678U, "?Compare@UsageIndexProperty@details_abi@wil@@QEBAHPEAX_K@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 8ULL, 2U, "read", 0x220FCU, "?Write@UsageIndexProperty@details_abi@wil@@QEBA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 16ULL, 8U, "write", 0x1C070U, "?Read@UsageIndexProperty@details_abi@wil@@QEAA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 16ULL, 8U, "read", 0x21DCCU, "?UpdateCount@UsageIndexProperty@details_abi@wil@@QEAAXI@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 24ULL, 8U, "write", 0x1C070U, "?Read@UsageIndexProperty@details_abi@wil@@QEAA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 24ULL, 8U, "read", 0x1C678U, "?Compare@UsageIndexProperty@details_abi@wil@@QEBAHPEAX_K@Z", "likely"},
    {"wil::details_abi::UsageIndexProperty", nullptr, 24ULL, 8U, "read", 0x220FCU, "?Write@UsageIndexProperty@details_abi@wil@@QEBA_NAEAPEAEPEAE@Z", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 0ULL, 4U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 4ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 6ULL, 2U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 8ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 16ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 24ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 32ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 40ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 48ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 48ULL, 8U, "read", 0x1D1E0U, "??1UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 48ULL, 8U, "read-write", 0x1D1E0U, "??1UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 56ULL, 2U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 56ULL, 1U, "read", 0x1D238U, "?Record@UsageIndexes@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 58ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 64ULL, 4U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 68ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 70ULL, 2U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 72ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 80ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 88ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 96ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 104ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 112ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 112ULL, 8U, "read", 0x1D1E0U, "??1UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 112ULL, 8U, "read-write", 0x1D1E0U, "??1UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 120ULL, 2U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 120ULL, 1U, "read", 0x1D238U, "?Record@UsageIndexes@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 122ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 128ULL, 4U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 132ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 134ULL, 2U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 136ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 144ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 152ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 160ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 168ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 176ULL, 8U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 176ULL, 8U, "read", 0x1D1E0U, "??1UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 176ULL, 8U, "read-write", 0x1D1E0U, "??1UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 184ULL, 2U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 184ULL, 1U, "read", 0x1D238U, "?Record@UsageIndexes@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::UsageIndexes", nullptr, 186ULL, 1U, "write", 0x1D0B8U, "??0UsageIndexes@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 0ULL, 8U, "read", 0x1C3E4U, "?ensure@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 0ULL, 16U, "write", 0x1F3F8U, "??0heap_buffer@details_abi@wil@@QEAA@$$QEAU012@@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 0ULL, 8U, "read", 0x223CCU, "?reserve@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 0ULL, 8U, "write", 0x223CCU, "?reserve@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 8ULL, 8U, "read", 0x1C3E4U, "?ensure@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 8ULL, 8U, "read", 0x1DAB4U, "?push_back@heap_buffer@details_abi@wil@@QEAA_NPEBX_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 8ULL, 8U, "read-write", 0x1DAB4U, "?push_back@heap_buffer@details_abi@wil@@QEAA_NPEBX_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 8ULL, 8U, "read", 0x223CCU, "?reserve@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 8ULL, 8U, "write", 0x223CCU, "?reserve@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 16ULL, 8U, "read", 0x1C3E4U, "?ensure@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 16ULL, 8U, "read", 0x1DAB4U, "?push_back@heap_buffer@details_abi@wil@@QEAA_NPEBX_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 16ULL, 8U, "write", 0x1F3F8U, "??0heap_buffer@details_abi@wil@@QEAA@$$QEAU012@@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 16ULL, 8U, "read", 0x223CCU, "?reserve@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 16ULL, 8U, "write", 0x223CCU, "?reserve@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 24ULL, 8U, "read", 0x223CCU, "?reserve@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::heap_buffer", nullptr, 24ULL, 8U, "write", 0x223CCU, "?reserve@heap_buffer@details_abi@wil@@QEAA_N_K@Z", "likely"},
    {"wil::last_error_context", nullptr, 0ULL, 1U, "write", 0x1F42CU, "??0last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 0ULL, 1U, "read", 0x1F604U, "??1last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 4ULL, 4U, "write", 0x1F42CU, "??0last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 4ULL, 4U, "read", 0x1F604U, "??1last_error_context@wil@@QEAA@XZ", "likely"},
    {"wistd", nullptr, 0ULL, 8U, "read", 0x1EDF4U, "??$?8XUprocess_heap_deleter@wil@@@wistd@@YA_NAEBV?$unique_ptr@XUprocess_heap_deleter@wil@@@0@$$T@Z", "likely"},
    {"wistd::__compressed_pair<void *, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "write", 0x1EDE0U, "??$?0PEAXUprocess_heap_deleter@wil@@@?$__compressed_pair@PEAXUprocess_heap_deleter@wil@@@wistd@@QEAA@$$QEAPEAX$$QEAUprocess_heap_deleter@wil@@@Z", "likely"},
    {"wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>", nullptr, 0ULL, 8U, "write", 0x1F730U, "??_G?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAAPEAXI@Z", "likely"},
    {"wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>", nullptr, 8ULL, 8U, "read", 0x1F660U, "??R?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAA_N$$QEAPEAX$$QEA_K01$$QEAI@Z", "likely"},
    {"wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>", nullptr, 8ULL, 16U, "read", 0x222E0U, "?__move@?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAAXPEAV?$__base@$$A6A_NPEAX_K01I@Z@23@@Z", "likely"},
    {"wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>", nullptr, 16ULL, 8U, "read", 0x1F660U, "??R?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAA_N$$QEAPEAX$$QEA_K01$$QEAI@Z", "likely"},
    {"wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>", nullptr, 24ULL, 8U, "read", 0x1F660U, "??R?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAA_N$$QEAPEAX$$QEA_K01$$QEAI@Z", "likely"},
    {"wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>", nullptr, 24ULL, 8U, "read", 0x222E0U, "?__move@?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAAXPEAV?$__base@$$A6A_NPEAX_K01I@Z@23@@Z", "likely"},
    {"wistd::function<bool __cdecl (void *, uint64_t, void *, uint64_t, unsigned int)>", nullptr, 112ULL, 8U, "read", 0x1DBE4U, "??1?$function@$$A6A_NPEAX_K01I@Z@wistd@@QEAA@XZ", "likely"},
    {"wistd::function<bool __cdecl (void *, uint64_t, void *, uint64_t, unsigned int)>", nullptr, 112ULL, 8U, "read", 0x1F6C8U, "??R?$function@$$A6A_NPEAX_K01I@Z@wistd@@QEBA_NPEAX_K01I@Z", "likely"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "write", 0x1EDD0U, "??$?0$00X@?$unique_ptr@XUprocess_heap_deleter@wil@@@wistd@@QEAA@PEAX@Z", "likely"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "read", 0x1F628U, "??4?$unique_ptr@XUprocess_heap_deleter@wil@@@wistd@@QEAAAEAV01@$$QEAV01@@Z", "likely"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "write", 0x1F628U, "??4?$unique_ptr@XUprocess_heap_deleter@wil@@@wistd@@QEAAAEAV01@$$QEAV01@@Z", "likely"},
    {nullptr, nullptr, 0, 0, nullptr, 0, nullptr, nullptr},
};
inline constexpr std::size_t field_observation_count = (sizeof(field_observations) / sizeof(field_observations[0])) - 1;
inline constexpr BaseLayout bases[] = {
    {".?AV?$__base@$$A6A_NPEAX_K01I@Z@__function@wistd@@", ".?AV?$__base@$$A6A_NPEAX_K01I@Z@__function@wistd@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AV?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@", ".?AV?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AV?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@", ".?AV?$__base@$$A6A_NPEAX_K01I@Z@__function@wistd@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVResultException@wil@@", ".?AVResultException@wil@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVResultException@wil@@", ".?AVexception@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {nullptr, nullptr, -1, false, nullptr, nullptr},
};
inline constexpr std::size_t base_count = (sizeof(bases) / sizeof(bases[0])) - 1;
inline constexpr VTableLayout vtables[] = {
    {"const BaseBrdResourceIdMap::`vftable'", 0x29000U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const ResourceIdMap::`vftable'", 0x29010U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const type_info::`vftable'", 0x29020U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::`vftable'", 0x290D0U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wistd::__function::__base<bool __cdecl (void *, uint64_t, void *, uint64_t, unsigned int)>::`vftable'", 0x29100U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wil::ResultException::`vftable'", 0x29130U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const ShellBrdResourceIdMap::`vftable'", 0x29140U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {nullptr, 0, 0, nullptr, nullptr},
};
inline constexpr std::size_t vtable_count = (sizeof(vtables) / sizeof(vtables[0])) - 1;
inline constexpr VTableSlotLayout vtable_slots[] = {
    {0x29000U, 0U, 0x23910U, nullptr, nullptr, true, 0},
    {0x29000U, 1U, 0xF8E0U, "?UpdateResourceId@BaseBrdResourceIdMap@@UEAAXKIPEAI@Z", "public: virtual void __cdecl BaseBrdResourceIdMap::UpdateResourceId(unsigned long, unsigned int, unsigned int *)", false, 0},
    {0x29010U, 0U, 0x23910U, nullptr, nullptr, true, 0},
    {0x29010U, 1U, 0x1E230U, nullptr, nullptr, true, 0},
    {0x29020U, 0U, 0x1E250U, nullptr, nullptr, true, 0},
    {0x290D0U, 0U, 0x1F730U, nullptr, nullptr, true, 0},
    {0x290D0U, 1U, 0x222E0U, nullptr, nullptr, true, 0},
    {0x290D0U, 2U, 0x222E0U, nullptr, nullptr, true, 0},
    {0x290D0U, 3U, 0x223C0U, "?destroy@?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAAXXZ", "public: virtual void __cdecl wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::destroy(void)", false, 0},
    {0x290D0U, 4U, 0x1F660U, "??R?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAA_N$$QEAPEAX$$QEA_K01$$QEAI@Z", "public: virtual bool __cdecl wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::operator()(void * &&, uint64_t &&, void * &&, uint64_t &&, unsigned int &&)", false, 0},
    {0x29100U, 0U, 0x1F730U, nullptr, nullptr, true, 0},
    {0x29100U, 1U, 0x1E230U, nullptr, nullptr, true, 0},
    {0x29100U, 2U, 0x1E230U, nullptr, nullptr, true, 0},
    {0x29100U, 3U, 0x1E230U, nullptr, nullptr, true, 0},
    {0x29100U, 4U, 0x1E230U, nullptr, nullptr, true, 0},
    {0x29130U, 0U, 0x1F760U, nullptr, nullptr, true, 0},
    {0x29130U, 1U, 0x22550U, "?what@ResultException@wil@@UEBAPEBDXZ", "public: virtual char const * __cdecl wil::ResultException::what(void) const", false, 0},
    {0x29140U, 0U, 0x23910U, nullptr, nullptr, true, 0},
    {0x29140U, 1U, 0x23950U, "?UpdateResourceId@ShellBrdResourceIdMap@@UEAAXKIPEAI@Z", "public: virtual void __cdecl ShellBrdResourceIdMap::UpdateResourceId(unsigned long, unsigned int, unsigned int *)", false, 0},
    {0, 0, 0, nullptr, nullptr, true, 0},
};
inline constexpr std::size_t vtable_slot_count = (sizeof(vtable_slots) / sizeof(vtable_slots[0])) - 1;
}
